# Root file for the composition.
#
# The options specific to the development should go in
# 'docker-compose.override.yml' which is automatically applied on top of this
# file when the option '-f' of docker-compose is not used

version: '2'
services:
  odoo:
    build: ./odoo/
    # Enable if you use oca/connector:
    command: "odoo --load=web,queue_job"
    depends_on:
      - db
    tty: true
    stdin_open: true
    ports:
      - 8069
      - 8072
    volumes:
      - "data-odoo:/data/odoo"
      - "data-odoo-db-cache:/.cachedb"
      - "data-odoo-pytest-cache:/odoo/.cache"
      - "./odoo/src:/odoo/src"
      - "./odoo/local-src:/odoo/local-src"
      - "./odoo/external-src:/odoo/external-src"
      - "./odoo/songs:/odoo/songs"
      - "./odoo/migration.yml:/odoo/migration.yml"
      - "./odoo/data:/odoo/data"
    environment:
      DB_USER: odoo
      DB_PASSWORD: odoo
      DB_NAME: odoodb
      ADMIN_PASSWD: mijaebohb8Thae1g
      RUNNING_ENV: dev
      ODOO_CONNECTOR_CHANNELS: root:4
      MARABUNTA_MODE: sample  # could be 'full' for the db with all the data
      MARABUNTA_ALLOW_SERIE: 'True'  # should not be set in production

  db:
    image: camptocamp/postgresql:pg9.5-latest
    ports:
      - 5432
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      PG_SYSTEM_SHARED_BUFFERS: 256MB
      PG_SYSTEM_MAINTENANCE_WORK_MEM: 256MB
      PG_SYSTEM_WAL_BUFFERS: 8MB
      PG_SYSTEM_EFFECTIVE_CACHE_SIZE: 1024MB
    volumes:
      - "data-db:/var/lib/postgresql/data"

  nginx:
    image: camptocamp/odoo-nginx:10.0-1.3.0
    depends_on:
      - odoo
    ports:
      - 80:80

## See `cups-test-server/README.md`.
  cups-server:
    build: ./cups-test-server/
    ports:
      - "6631:631"
    expose:
      - 631
    volumes:
      - "/tmp/cups-pdf:/var/spool/cups-pdf:rw"
    environment:
      CUPS_USER_ADMIN: admin
      CUPS_USER_PASSWORD: secr3t

volumes:
  data-odoo:
  data-db:
  data-odoo-db-cache:
  data-odoo-pytest-cache:
